name: Laravel CD to Staging

on:
  push:
    branches:
      - development

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, bcmath, xml, curl, mysql

      - name: Run deployment on EC2 server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /var/www/myapp

            echo "✅ Tambahkan safe directory Git"
            git config --global --add safe.directory /var/www/myapp

            echo "✅ Pull source code dari GitHub"
            git reset --hard
            git clean -fd
            git pull origin development

            echo "✅ Install Composer dependencies"
            composer install --no-dev --prefer-dist --no-progress

            echo "✅ Install & Build Vite"
            npm ci
            npm run build

            echo "✅ Artisan commands"
            php artisan migrate --force
            php artisan config:cache
            php artisan storage:link || true
            php artisan optimize

            echo "✅ Fix permission"
            sudo chown -R www-data:www-data /var/www/myapp
            sudo chmod -R 775 /var/www/myapp/storage /var/www/myapp/bootstrap/cache
