name: Laravel CD to Staging

on:
  push:
    branches:
      - development

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, bcmath, xml, curl, mysql

      - name: Run remote SSH commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /var/www/myapp
            git pull origin development
            composer install --no-dev --prefer-dist --no-progress
            npm ci
            npm run build
            php artisan migrate --force
            php artisan config:cache
            php artisan storage:link || true
            php artisan optimize
            chown -R www-data:www-data .
            chmod -R 775 storage bootstrap/cache
            sudo chown -R www-data:www-data /var/www/myapp
            sudo chmod -R 775 storage bootstrap/cache
          
  

