name: ALERT Issue Reminder

on:
  schedule:
    - cron: '*/5 * * * *' # Setiap 5 menit
  workflow_dispatch:

jobs:
  remind:
    runs-on: ubuntu-latest
    steps:
      - name: Check Assigned Issues with Custom Token
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GH_PAT }}
          script: |
            const issues = await github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
            });

            for (const issue of issues.data) {
              if (issue.assignees.length > 0) {
                const assignees = issue.assignees.map(a => `@${a.login}`).join(' ');
                await github.rest.issues.createComment({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: issue.number,
                  body: `👋 ${assignees} Kerjakan dulu zod [ reminder: please take a look at this issue!], this alert will show every 2 hours!`,
                });
              }
            }

