name: ALERT Issue Reminder

on:
  schedule:
   - cron: '0 0 */2 * *'

  workflow_dispatch:

jobs:
  remind:
    runs-on: ubuntu-latest
    steps:
      - name: Check Assigned Issues with Custom Token
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GH_PAT }}
          script: |
            const issues = await github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
            });

            for (const issue of issues.data) {
              if (issue.assignees.length > 0) {
                const assignees = issue.assignees.map(a => `@${a.login}`).join(' ');
                await github.rest.issues.createComment({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: issue.number,
                  body: `Reminder: 👋 ${assignees} Kerjakan dulu zod - You have been assigned to this issue. Please take action if you haven't already. This is an automated message sent every 2 days to ensure issues receive timely attention. Thank you! 🤖 `,
                });
              }
            }

